shop: id
products:
- labels: [weigh]
  category: vegetables
  type: broccoli
- labels: [due]
  prices: {minimum: 0.89, maximum: 0.99}
  category: bread
  portions: 22
  weight: 150g
  gtin: 01234567890123
- prices: [2.00, 2.50, 3.00]
  bonuses: [disco]
  type: chocolate
  sku: abc123
  range:
  - prices: [2.00]
    bonuses: []
    description: Small
    sku: abc123s
  - prices: [2.50]
    description: Medium size
    sku: abc123-m
